### PR TITLE
fix: download the right version of biomejs when used libc is musl

### LINKED ISSUE #15: Cannot run in docker container based on alpine (musl libc)
Hello,

i'm working with a docker image based on [alpine](https://hub.docker.com/_/alpine) and i have tried to use BiomejsBundle.

But when i run the command, the following error occurs:
```shell
$ php bin/console biomejs:check .

 ! [NOTE] Executing Biome.js "check" (pass -v to see more details).                                                     

sh: exec: line 0: /usr/local/src/app/var/biomejs/v1.8.3/biome-linux-x64: not found
                                                                                                                        
 [ERROR] Biome.js check failed: see output above.            
```
I have tried many versions of the bin biome-linux-x64 and the same error occurs.

This is because Alpine use the musl version of the libc which seems to be not compatible with the bin biome-linux-x64 (build with the standard libc).

So would it be possible to build this bin with the musl version of the libc ?

Thank you in advance for your reply.

And thank you for this bundle ! :)

### PR DESCRIPTION
**Pull request by ralauge-aramis**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | Close #15

### CODE REVIEW

File: src/BiomeJsBinary.php [hunk 1]
```diff
@@ -154,15 +154,24 @@ public static function getBinaryName(): string
...
         $machine = strtolower(php_uname('m'));
 
+        $isMusl = false;
+        ob_start();
+        phpinfo(INFO_GENERAL);
+        $buildinfo = ob_get_contents();
+        ob_end_clean();
+        if (preg_match('/--build=.*?-linux-musl/', $buildinfo)) {
+            $isMusl = true;
+        }
```
Comment (Kocal) [inline src/BiomeJsBinary.php:164]: Although interesting and quite clever, I'm not fan about this solution.

Can we assume that if we are running on Alpine, then we will have to download the Biomejs "musl" binary?

If yes, then we can check on file `/etc/alpine-release` presence.

WDYT?

Comment (srbetasign) [reply src/BiomeJsBinary.php:164]: Checking whether we're in Alpine doesn't seem to solve the problem properly because :
- it would not be suitable for the other docker images (or environments) who are or will be based on musl.
- Alpine may decide to use the standard libc in the future

In fact, the core of the problem is the use of musl not Alpine.

This proposal relies on the presence of musl rather than the presence of Alpine, which avoids the situations mentioned.

Comment (Kocal) [reply src/BiomeJsBinary.php:164]: Hum, alright, that's what I thought 😕

**Comment by Kocal** [comment]
@ralauge-aramis @srbetasign I did some modifications, can you confirm me it's still working for you?

File: src/BiomeJsBinary.php [hunk 2]
```diff
@@ -182,4 +173,26 @@ public static function getBinaryName(): string
...
+     * Whether the current PHP environment is using musl libc.
+     * This is used to determine the correct Biome.js binary to download.
+     */
+    private static function isMusl(): bool
+    {
+        static $isMusl = null;
+
+        if (null !== $isMusl) {
+            return false;
+        }
```
Comment (srbetasign) [inline src/BiomeJsBinary.php:187]: Should not it return $isMusl instead of false ?
It would return false even if $isMusl is true.

Comment (srbetasign) [reply src/BiomeJsBinary.php:187]: @ralauge-aramis (who does not speak too much :p ) has tested with "return false", and it fails :/

With "return $isMusl", it works as expected :)

Comment (Kocal) [reply src/BiomeJsBinary.php:187]: Oops yes, it should be `return $isMusl`! Thanks :)

**Comment by Kocal** [comment]
Merged and released in https://github.com/Kocal/BiomeJsBundle/releases/tag/v1.2.1 :)
